import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'
import { scanEnvOwnership, SCAN_PATTERNS_VERSION, parsePrismaDatasourceEnv } from '../env-ownership-scan'
import { renderEnvManifest, READ_BY_NONE_ALLOWED, MANIFEST_ENTRY_KEYS } from '../../../scripts/gen-env-ownership'
import { checkEnv } from '../env'
import { assertNoProductionCredentials } from './_disposable-test-env'

// ════════════════════════════════════════════════════════════════════════
//  ENVIRONMENT OWNERSHIP — the API and the worker are SEPARATE Railway
//  services with SEPARATE variable sets (incident 2026-09-14: the campaign
//  drafter's flag existed on the API and was missing on the worker that runs
//  it, so the feature silently never ran while the admin said ACTIVE).
//
//  docs/env-ownership.json declares, for every variable the code reads, which
//  service reads it. This suite recomputes that from the import graph and fails
//  when the two disagree — so a new variable read, or a variable that starts
//  being read by the worker, cannot ship without the manifest (and therefore
//  the deploy checklist) saying so.
//
//  2026-09-15: the manifest used to be able to be FALSELY GREEN. It was
//  generated by the same literal-only scanner that verified it, so a read the
//  scanner could not see was absent from both sides and every test passed.
//  That is how STRIPE_SECRET_KEY came to be missing from a checklist for a
//  service that HALTS without it, and how DATABASE_URL came to say "readBy:
//  none". The tests below therefore anchor the manifest against things the
//  scanner does not produce: checkEnv()'s own declarations, prisma/schema.prisma
//  parsed independently, and a hand-listed set of the variables the old scanner
//  was known to miss. Plus: every computed `process.env[…]` site must be
//  registered, so a new one fails here instead of disappearing.
// ════════════════════════════════════════════════════════════════════════

assertNoProductionCredentials()

const ROOT = resolve(__dirname, '../../..')
type Entry = {
  readBy: Array<'api' | 'worker' | 'script' | 'none'>
  secret: boolean
  mustMatch?: boolean
  requiredBy?: string[]
  requiredWhenEmailOn?: boolean
  checkedBy?: string[]
  note?: string
}
// core.autocrlf is on, so a Windows checkout has CRLF while the generator (and
// CI) write LF. Compare content, not line endings.
const RAW = readFileSync(resolve(ROOT, 'docs/env-ownership.json'), 'utf8').replace(/\r\n/g, '\n')
const manifest = JSON.parse(RAW) as { version: number; scanPatternsVersion?: number; vars: Record<string, Entry> }
const scan = scanEnvOwnership(ROOT)

const sorted = (a: readonly string[]) => [...a].sort()

test('the scan found both entrypoints (a broken graph must not pass vacuously)', () => {
  assert.ok(scan.workerModules > 50, `worker graph too small (${scan.workerModules}) — src/worker-host.ts imports not resolved?`)
  assert.ok(scan.apiModules > 100, `api graph too small (${scan.apiModules})`)
  assert.ok(scan.readers.size > 50, 'too few environment reads found — the scan is broken')
})

test('the broadened scan is the one in use (a silent revert to literal-only must fail)', () => {
  assert.ok(SCAN_PATTERNS_VERSION >= 2, 'the literal-only scanner missed every computed read; do not go back to it')
  assert.equal(manifest.scanPatternsVersion, SCAN_PATTERNS_VERSION, 'regenerate docs/env-ownership.json: it was built by a different scanner')
})

test('every variable the code reads is declared in docs/env-ownership.json', () => {
  const missing = [...scan.readers.keys()].filter((n) => !manifest.vars[n]).sort()
  assert.deepEqual(missing, [], `undeclared environment variables — add them to docs/env-ownership.json: ${missing.join(', ')}`)
})

test('no declared variable is stale (read nowhere any more)', () => {
  const stale = Object.keys(manifest.vars).filter((n) => !scan.readers.has(n)).sort()
  assert.deepEqual(stale, [], `docs/env-ownership.json lists variables no code reads: ${stale.join(', ')}`)
})

test('the declared readers match the import graph for every variable', () => {
  const wrong: string[] = []
  for (const [name, r] of scan.readers) {
    const e = manifest.vars[name]
    if (!e) continue
    const services = [...(r.api ? ['api'] : []), ...(r.worker ? ['worker'] : [])]
    const expected = services.length ? services : r.script ? ['script'] : ['none']
    if (JSON.stringify(sorted(e.readBy)) !== JSON.stringify(sorted(expected))) {
      wrong.push(`${name}: manifest ${JSON.stringify(e.readBy)} vs code ${JSON.stringify(expected)}`)
    }
  }
  assert.deepEqual(wrong, [], `regenerate or correct docs/env-ownership.json:\n${wrong.join('\n')}`)
})

test('the incident variable is declared as read by BOTH services and must match', () => {
  const e = manifest.vars.EMAIL_MARKETING_AGENT_ENABLED
  assert.ok(e, 'EMAIL_MARKETING_AGENT_ENABLED must be declared')
  assert.ok(e.readBy.includes('worker'), 'the discovery sweep runs on the worker')
  assert.ok(e.readBy.includes('api'), 'the admin card reads it on the API')
  assert.equal(e.mustMatch, true, 'API and worker must carry the same value')
})

test('every value that must be identical on both services is read by both', () => {
  for (const [name, e] of Object.entries(manifest.vars)) {
    if (!e.mustMatch) continue
    assert.ok(e.readBy.includes('api') && e.readBy.includes('worker'), `${name} is mustMatch but is not read by both services`)
  }
})

test('the manifest carries names and flags only — never a value', () => {
  assert.ok(
    !/re_[A-Za-z0-9]{8,}|sk_(live|test)_|whsec_|postgres(ql)?:\/\/|redis:\/\//.test(RAW),
    'a secret-shaped value leaked into the manifest',
  )
  for (const [name, e] of Object.entries(manifest.vars)) {
    assert.deepEqual(
      Object.keys(e).filter((k) => !(MANIFEST_ENTRY_KEYS as readonly string[]).includes(k)),
      [],
      `${name} carries a key the manifest schema does not define`,
    )
  }
})

test('SMS is gone: no Twilio variable is read anywhere', () => {
  const twilio = [...scan.readers.keys()].filter((n) => n.startsWith('TWILIO'))
  assert.deepEqual(twilio, [], 'Move It Clear It no longer sends SMS (owner, 2026-09-15)')
})

// ── THE ANCHORS: things the scanner does not produce ────────────────────

test('src/lib/env.ts declarations were parsed, and match what checkEnv() actually reports', () => {
  // Non-vacuous: if the structural parse silently returned nothing, every
  // requiredBy assertion below would pass by having nothing to check.
  assert.ok(scan.declarations.length >= 20, `only ${scan.declarations.length} env.ts declarations parsed — the parser lost track of the EnvVar[] arrays`)

  // Independent anchor: checkEnv() is the function that halts the worker, so
  // ask IT which keys exist rather than trusting the parse.
  const reported = new Set(Object.values(checkEnv().groups).flat().map((v) => v.key))
  const parsed = new Set(scan.declarations.map((d) => d.key))
  assert.deepEqual(sorted([...parsed]), sorted([...reported]), 'the parsed declarations and checkEnv()\'s own report disagree')
  for (const k of ['DATABASE_URL', 'REDIS_URL', 'APP_URL', 'STRIPE_SECRET_KEY', 'DISCORD_PUBLIC_KEY', 'RESEND_API_KEY']) {
    assert.ok(parsed.has(k), `${k} must be one of checkEnv()'s declarations`)
  }
})

test('every key checkEnv() REQUIRES is in the manifest, requiredBy both services', () => {
  // Both entrypoints run checkEnv(): src/worker-host.ts at boot (STARTUP
  // HALTED → exit 1) and app/api/health/route.ts on every health request. An
  // operator who trims the worker to the manifest must not remove one of these.
  const envTs = scan.reaches('src/lib/env.ts')
  assert.ok(envTs.api && envTs.worker, 'both services must reach src/lib/env.ts, or requiredBy below is meaningless')

  const problems: string[] = []
  for (const d of scan.declarations) {
    const e = manifest.vars[d.key]
    if (!e) {
      problems.push(`${d.key} (${d.group}) is declared in env.ts but absent from the manifest`)
      continue
    }
    if (!e.readBy.includes('api') || !e.readBy.includes('worker')) {
      problems.push(`${d.key}: checkEnv() reads it on both services but readBy is ${JSON.stringify(e.readBy)}`)
    }
    if (d.required) {
      assert.deepEqual(sorted(e.requiredBy ?? []), ['api', 'worker'], `${d.key} is required by checkEnv() on both services`)
      if (d.conditional === 'email') {
        assert.equal(e.requiredWhenEmailOn, true, `${d.key} is required only when email is on — say so`)
      }
    } else {
      assert.deepEqual(sorted(e.checkedBy ?? []), ['api', 'worker'], `${d.key} is presence-checked by checkEnv() on both services`)
      assert.equal(e.requiredBy, undefined, `${d.key} is optional; it must not claim requiredBy`)
    }
  }
  assert.deepEqual(problems, [], problems.join('\n'))
})

test('the shared infrastructure is declared shared: DATABASE_URL and REDIS_URL, both services, mustMatch', () => {
  for (const key of ['DATABASE_URL', 'REDIS_URL']) {
    const e = manifest.vars[key]
    assert.ok(e, `${key} must be declared`)
    assert.deepEqual(sorted(e.readBy), ['api', 'worker'], `${key} is read by BOTH services`)
    assert.equal(e.mustMatch, true, `${key} must carry the same value on both, or jobs go to a queue nothing listens on`)
    assert.equal(e.secret, true)
    assert.ok(e.note && e.note.length > 40, `${key} needs a note saying what breaks when the two services disagree`)
  }
})

test('prisma datasource env() keys are declared, parsed independently of the scanner', () => {
  const fields = parsePrismaDatasourceEnv(readFileSync(resolve(ROOT, 'prisma/schema.prisma'), 'utf8'))
  const url = fields.find((f) => f.field === 'url')
  assert.ok(url, 'the datasource must read its url from env()')
  assert.deepEqual(sorted(manifest.vars[url.name].readBy), ['api', 'worker'], `${url.name} is what PrismaClient connects with on both services`)

  const shadow = fields.find((f) => f.field === 'shadowDatabaseUrl')
  if (shadow) {
    const e = manifest.vars[shadow.name]
    assert.ok(e, `${shadow.name} must be declared`)
    assert.deepEqual(e.readBy, ['none'], 'only the migrate CLI reads the shadow database URL')
    assert.ok(READ_BY_NONE_ALLOWED[shadow.name], 'and that must be on the allowlist with a reason')
  }
})

test('readBy ["none"] is a claim about the code, and needs a written reason', () => {
  const unexplained = Object.entries(manifest.vars)
    .filter(([n, e]) => e.readBy.length === 1 && e.readBy[0] === 'none' && !READ_BY_NONE_ALLOWED[n])
    .map(([n]) => n)
  assert.deepEqual(
    unexplained,
    [],
    `these claim nothing reads them. Either the scan cannot see the read (add a DYNAMIC_ENV_RULES entry) or it is genuinely dead (add it to READ_BY_NONE_ALLOWED): ${unexplained.join(', ')}`,
  )
  for (const [name, reason] of Object.entries(READ_BY_NONE_ALLOWED)) {
    const e = manifest.vars[name]
    if (!e) continue
    assert.ok(reason.length > 40, `${name}'s allowlist reason must actually explain itself`)
    assert.equal(e.note, reason, `${name}'s manifest note must carry the allowlist reason`)
  }
})

test('regression: every variable the literal-only scanner used to miss is now attributed correctly', () => {
  // Hand-listed from the 2026-09-15 audit. These are exactly the entries an
  // operator would have got wrong by trusting the old manifest.
  const expected: Record<string, { readBy: string[]; mustMatch?: boolean }> = {
    STRIPE_SECRET_KEY: { readBy: ['api', 'worker'], mustMatch: true },
    STRIPE_WEBHOOK_SECRET: { readBy: ['api', 'worker'], mustMatch: true },
    DISCORD_PUBLIC_KEY: { readBy: ['api', 'worker'] },
    DISCORD_APPLICATION_ID: { readBy: ['api', 'worker'] },
    DATABASE_URL: { readBy: ['api', 'worker'], mustMatch: true },
    EMAIL_CAP_PER_DAY: { readBy: ['api', 'worker'], mustMatch: true },
    EMAIL_CAP_PER_WEEK: { readBy: ['api', 'worker'], mustMatch: true },
    EMAIL_CAP_PER_MONTH: { readBy: ['api', 'worker'], mustMatch: true },
    EMAIL_QUIET_START_HOUR: { readBy: ['api', 'worker'], mustMatch: true },
    EMAIL_QUIET_END_HOUR: { readBy: ['api', 'worker'], mustMatch: true },
    EMAIL_TRANSACTIONAL_GAP_MINUTES: { readBy: ['api', 'worker'], mustMatch: true },
  }
  for (const [name, want] of Object.entries(expected)) {
    const e = manifest.vars[name]
    assert.ok(e, `${name} must be declared — the literal-only scanner could not see it`)
    assert.deepEqual(sorted(e.readBy), sorted(want.readBy), `${name} readBy`)
    if (want.mustMatch) assert.equal(e.mustMatch, true, `${name} must carry the same value on both services`)
  }
  for (const name of ['DISCORD_PAYMENTS_WEBHOOK_URL', 'DISCORD_PAYMENTS_CHANNEL_ID', 'DISCORD_PAYMENTS_AVATAR_URL', 'ALLOW_EMAIL_AGENT_PRODUCTION_WRITES', 'NEXT_PUBLIC_MARKETING_SITE_URL']) {
    assert.ok(manifest.vars[name], `${name} must be declared`)
  }
})

test('the feature flags are documented with which service must carry them', () => {
  // A flag set on one service only is the 2026-09-14 incident repeating.
  const flags = [
    'EMAIL_SENDING_ENABLED',
    'OUTBOX_ENABLED',
    'OUTBOX_EMAIL_DRYRUN',
    'EMAIL_JOURNEYS_ENABLED',
    'MARKETING_FOLLOWUPS_ENABLED',
    'EMAIL_PROMOTIONS_ENABLED',
    'EMAIL_MARKETING_AGENT_ENABLED',
    'REFERRAL_PROGRAM_ENABLED',
  ]
  for (const name of flags) {
    const e = manifest.vars[name]
    assert.ok(e, `${name} must be declared`)
    assert.ok(e.note && e.note.length > 40, `${name} needs a note saying which service acts on it`)
  }
  // Every flag except the worker-only dry run must be identical on both.
  for (const name of flags.filter((f) => f !== 'OUTBOX_EMAIL_DRYRUN')) {
    assert.equal(manifest.vars[name].mustMatch, true, `${name} must be the same on both services`)
  }
  assert.ok(/worker/i.test(manifest.vars.OUTBOX_EMAIL_DRYRUN.note ?? ''), 'OUTBOX_EMAIL_DRYRUN is worker behaviour; the note must say so')
})

test('the provider and sender identity are documented as shared', () => {
  for (const name of ['RESEND_API_KEY', 'RESEND_WEBHOOK_SECRET', 'EMAIL_FROM', 'EMAIL_REPLY_TO']) {
    const e = manifest.vars[name]
    assert.ok(e, `${name} must be declared`)
    assert.equal(e.mustMatch, true, `${name} must be identical on both services`)
    assert.ok(e.note && e.note.length > 30, `${name} needs a note`)
  }
})

test('no computed process.env access is unregistered', () => {
  const detail = scan.unregisteredSites
    .map((u) => {
      const sites = scan.dynamicSites.filter((d) => d.file === u.file).map((d) => `      ${d.file}:${d.line}  ${d.snippet}`)
      return `  ${u.file}: found ${u.found} computed read(s), DYNAMIC_ENV_RULES declares ${u.registered}\n${sites.join('\n')}`
    })
    .join('\n')
  assert.deepEqual(
    scan.unregisteredSites,
    [],
    'a computed environment read the manifest cannot resolve. Declare where its keys come from in DYNAMIC_ENV_RULES (src/lib/env-ownership-scan.ts):\n' + detail,
  )
})

test('no dynamic rule is stale', () => {
  assert.deepEqual(scan.staleRules, [], `DYNAMIC_ENV_RULES describes code that no longer exists:\n${scan.staleRules.join('\n')}`)
})

test('the committed manifest is exactly what a fresh scan produces', () => {
  // The drift gate. Without it the manifest is a snapshot of whenever someone
  // last remembered to run the generator.
  assert.equal(renderEnvManifest(ROOT), RAW, 'run `npx tsx scripts/gen-env-ownership.ts` and commit docs/env-ownership.json')
})
