import { test } from 'node:test'
import assert from 'node:assert/strict'
import { mkdirSync, mkdtempSync, rmSync, writeFileSync } from 'node:fs'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { scanEnvOwnership, parseEnvDeclarations, parsePrismaDatasourceEnv, type DynamicEnvRule } from '../env-ownership-scan'
import { assertNoProductionCredentials } from './_disposable-test-env'

// ════════════════════════════════════════════════════════════════════════
//  THE SCANNER ITSELF, against a synthetic repository.
//
//  env-ownership.test.ts checks that the manifest matches the scan. That is
//  circular unless something also proves the SCAN sees what it claims to see:
//  a scanner that quietly stopped detecting `env.X` would agree with a manifest
//  regenerated by the same scanner, and both would be wrong. So this suite
//  builds a small fake repository containing one instance of every supported
//  access shape and asserts each one is found AND attributed to the right
//  service — and that an access shape nobody declared is REPORTED rather than
//  dropped.
//
//  Nothing here touches the real environment, a database, Redis or a provider.
// ════════════════════════════════════════════════════════════════════════

assertNoProductionCredentials()

type Fixture = { root: string; cleanup: () => void }

function writeFixture(files: Record<string, string>): Fixture {
  const root = mkdtempSync(join(tmpdir(), 'env-scan-'))
  for (const [rel, body] of Object.entries(files)) {
    const full = join(root, ...rel.split('/'))
    mkdirSync(join(full, '..'), { recursive: true })
    writeFileSync(full, body, 'utf8')
  }
  return { root, cleanup: () => rmSync(root, { recursive: true, force: true }) }
}

/**
 * A repository with one of everything:
 *   src/a.ts        worker-only  — literal, bracket literal, destructure,
 *                                  ProcessEnv parameter (dot and bracket),
 *                                  and one computed read covered by a rule
 *   src/b.ts        api-only     — a helper call, `requiredEnv('CALL_KEY')`
 *   src/registry.ts both         — a `flag:` property another file indexes with
 *   src/lib/db.ts   both         — constructs PrismaClient, so the datasource
 *                                  url in prisma/schema.prisma belongs to it
 *   src/dev-only.ts neither      — a dev entrypoint nothing deploys
 *   scripts/tool.ts neither      — a maintenance script
 */
const BASE_FILES: Record<string, string> = {
  'src/worker-host.ts': [
    "import './a'",
    "import './lib/db'",
    "import './registry'",
    'export const host = true',
  ].join('\n'),
  'src/a.ts': [
    'const KEY_FROM_A_LIST = "LIST_KEY"',
    'export const one = process.env.LIT_ONE',
    "export const two = process.env['LIT_TWO']",
    'const { DESTR_KEY } = process.env',
    'export const destructured = DESTR_KEY',
    'export function readParam(env: NodeJS.ProcessEnv = process.env) {',
    "  return [env.PARAM_KEY, env['PARAM_BRACKET_KEY']]",
    '}',
    'export const computed = process.env[KEY_FROM_A_LIST]',
  ].join('\n'),
  'src/b.ts': [
    'function requiredEnv(name: string): string {',
    '  const v = process.env[name]',
    '  if (!v) throw new Error(name)',
    '  return v',
    '}',
    "export const callKey = requiredEnv('CALL_KEY')",
  ].join('\n'),
  'src/registry.ts': [
    "export const TEMPLATES = [{ key: 'welcome', flag: 'PROP_KEY' }, { key: 'plain', flag: null }]",
    'export function enabled(t: { flag: string | null }) {',
    "  return t.flag ? process.env[t.flag] === 'true' : true",
    '}',
  ].join('\n'),
  'src/lib/db.ts': ["import { PrismaClient } from '@prisma/client'", 'export const prisma = new PrismaClient()'].join('\n'),
  'src/dev-only.ts': ['export const port = process.env.DEV_ONLY_KEY'].join('\n'),
  'scripts/tool.ts': ['export const base = process.env.SCRIPT_TOOL_KEY'].join('\n'),
  'app/x/route.ts': ["import '@/b'", "import '@/lib/db'", "import '@/registry'", 'export const GET = () => null'].join('\n'),
  'prisma/schema.prisma': [
    'datasource db {',
    '  provider          = "postgresql"',
    '  url               = env("PRISMA_KEY")',
    '  shadowDatabaseUrl = env("PRISMA_SHADOW")',
    '}',
  ].join('\n'),
}

const BASE_RULES: DynamicEnvRule[] = [
  { file: 'src/a.ts', sites: 1, why: 'fixture', keys: { kind: 'explicit', names: ['LIST_KEY'] } },
  { file: 'src/b.ts', sites: 1, why: 'fixture', keys: { kind: 'call', callees: ['requiredEnv'], scope: 'file' } },
  { file: 'src/registry.ts', sites: 1, why: 'fixture', keys: { kind: 'property', property: 'flag', from: ['src/registry.ts'] } },
]

test('every supported access shape is detected and attributed to the right service', () => {
  const fx = writeFixture(BASE_FILES)
  try {
    const scan = scanEnvOwnership(fx.root, { rules: BASE_RULES })
    const at = (name: string) => {
      const r = scan.readers.get(name)
      assert.ok(r, `${name} was not detected at all`)
      return { api: r.api, worker: r.worker, script: r.script }
    }

    const WORKER_ONLY = { api: false, worker: true, script: false }
    const API_ONLY = { api: true, worker: false, script: false }
    const BOTH = { api: true, worker: true, script: false }
    const SCRIPT = { api: false, worker: false, script: true }

    assert.deepEqual(at('LIT_ONE'), WORKER_ONLY, 'process.env.X')
    assert.deepEqual(at('LIT_TWO'), WORKER_ONLY, "process.env['X']")
    assert.deepEqual(at('DESTR_KEY'), WORKER_ONLY, 'const { X } = process.env')
    assert.deepEqual(at('PARAM_KEY'), WORKER_ONLY, 'env.X on a NodeJS.ProcessEnv parameter')
    assert.deepEqual(at('PARAM_BRACKET_KEY'), WORKER_ONLY, "env['X'] on a NodeJS.ProcessEnv parameter")
    assert.deepEqual(at('LIST_KEY'), WORKER_ONLY, 'a computed read resolved by an explicit rule')
    assert.deepEqual(at('CALL_KEY'), API_ONLY, "requiredEnv('X') resolved by a call rule")
    assert.deepEqual(at('PROP_KEY'), BOTH, 'a registry flag: property, read by both services')
    assert.deepEqual(at('PRISMA_KEY'), BOTH, 'the prisma datasource url belongs to whoever constructs PrismaClient')
    assert.deepEqual(at('DEV_ONLY_KEY'), SCRIPT, 'a file neither service reaches')
    assert.deepEqual(at('SCRIPT_TOOL_KEY'), SCRIPT, 'scripts/ is scanned and reported as script')

    // The shadow database URL is read by the migrate CLI, not by any service
    // and not by any scanned file — the one case where "none" is the truth.
    assert.deepEqual(at('PRISMA_SHADOW'), { api: false, worker: false, script: false })
    assert.deepEqual(scan.readers.get('PRISMA_SHADOW')!.files, ['prisma/schema.prisma'])

    assert.deepEqual(scan.unregisteredSites, [], 'every computed site in the fixture is declared')
    assert.deepEqual(scan.staleRules, [])
    assert.ok(scan.workerModules >= 4 && scan.apiModules >= 4, 'the fixture graph resolved')
  } finally {
    fx.cleanup()
  }
})

test('a computed read nobody declared is REPORTED, not silently dropped', () => {
  // This is the failure mode the whole design exists to prevent: a new
  // `process.env[x]` that the scanner cannot resolve must fail CI, not vanish
  // from the deploy checklist.
  const fx = writeFixture({
    ...BASE_FILES,
    'src/c.ts': ['export function pick(name: string) {', '  return process.env[name]', '}'].join('\n'),
    'src/worker-host.ts': ["import './a'", "import './c'", "import './lib/db'", "import './registry'", 'export const host = true'].join('\n'),
  })
  try {
    const scan = scanEnvOwnership(fx.root, { rules: BASE_RULES })
    assert.equal(scan.unregisteredSites.length, 1)
    assert.equal(scan.unregisteredSites[0].file, 'src/c.ts')
    assert.equal(scan.unregisteredSites[0].found, 1)
    assert.equal(scan.unregisteredSites[0].registered, 0)
    const site = scan.dynamicSites.find((d) => d.file === 'src/c.ts')
    assert.ok(site && site.line === 2, 'the report must name the line so it can be fixed')
  } finally {
    fx.cleanup()
  }
})

test('a rule that describes code which no longer reads the environment is stale', () => {
  const fx = writeFixture(BASE_FILES)
  try {
    const scan = scanEnvOwnership(fx.root, {
      rules: [...BASE_RULES, { file: 'src/dev-only.ts', sites: 1, why: 'fixture', keys: { kind: 'explicit', names: ['GONE_KEY'] } }],
    })
    assert.equal(scan.staleRules.length, 1)
    assert.match(scan.staleRules[0], /src\/dev-only\.ts/)
  } finally {
    fx.cleanup()
  }
})

test('an interpolated key is treated as computed, not mistaken for a literal', () => {
  // `process.env[`EMAIL_DNS_${record}`]` is how the real email-admin DNS
  // overrides are read. Counting it as the literal "EMAIL_DNS_" would be worse
  // than missing it, so it must land in the computed set.
  const fx = writeFixture({
    ...BASE_FILES,
    'src/tpl.ts': ['export function dns(record: string) {', '  return process.env[`EMAIL_DNS_${record}`]', '}'].join('\n'),
    'src/worker-host.ts': ["import './a'", "import './tpl'", "import './lib/db'", "import './registry'", 'export const host = true'].join('\n'),
  })
  try {
    const scan = scanEnvOwnership(fx.root, { rules: BASE_RULES })
    assert.ok(
      scan.dynamicSites.some((d) => d.file === 'src/tpl.ts'),
      'an interpolated template key must be reported as a computed site',
    )
    assert.ok(![...scan.readers.keys()].some((k) => k.startsWith('EMAIL_DNS')), 'and must not be harvested as a bogus literal name')
  } finally {
    fx.cleanup()
  }
})

test('type-only imports do not extend a service graph', () => {
  const fx = writeFixture({
    ...BASE_FILES,
    'src/types-only.ts': ['export type T = { a: number }', 'export const secret = process.env.TYPE_ONLY_KEY'].join('\n'),
    'src/worker-host.ts': [
      "import './a'",
      "import type { T } from './types-only'",
      "import './lib/db'",
      "import './registry'",
      'export const host: T | null = null',
    ].join('\n'),
  })
  try {
    const scan = scanEnvOwnership(fx.root, { rules: BASE_RULES })
    const r = scan.readers.get('TYPE_ONLY_KEY')
    assert.ok(r, 'the read is still found')
    assert.equal(r.worker, false, 'a type-only import is erased at compile time and runs no code')
    assert.equal(r.script, true)
  } finally {
    fx.cleanup()
  }
})

test('parseEnvDeclarations reads EnvVar[] entries and never a placeholder VALUE', () => {
  // The real src/lib/env.ts holds `const PLACEHOLDERS = new Set(['',
  // 'REPLACE_ME', …])`. Harvesting uppercase string literals would turn
  // REPLACE_ME into an environment variable, which is how a manifest starts
  // listing things that do not exist.
  const source = [
    'type EnvVar = { key: string; required: boolean; note?: string }',
    'const REQUIRED_CORE: EnvVar[] = [',
    "  { key: 'DATABASE_URL', required: true, note: 'Postgres' },",
    "  { key: 'APP_URL', required: true },",
    ']',
    'const REQUIRED_EMAIL: EnvVar[] = [',
    "  { key: 'RESEND_API_KEY', required: true },",
    ']',
    'const OPTIONAL_NOTIFY: EnvVar[] = [',
    "  { key: 'EMAIL_REPLY_TO', required: false },",
    ']',
    'const UNUSED_LIST: EnvVar[] = [',
    "  { key: 'NOT_IN_GROUPS', required: true },",
    ']',
    "const PLACEHOLDERS = new Set(['', 'REPLACE_ME', 'SOME_OTHER_PLACEHOLDER'])",
    'const GROUPS: Record<string, EnvVar[]> = {',
    '  Core: REQUIRED_CORE,',
    '  Notifications: OPTIONAL_NOTIFY,',
    '  Email: REQUIRED_EMAIL,',
    '}',
    'export const unused = PLACEHOLDERS',
  ].join('\n')

  const decls = parseEnvDeclarations(source)
  assert.deepEqual(
    decls.map((d) => `${d.group}:${d.key}:${d.required}:${d.conditional}`).sort(),
    [
      'Core:APP_URL:true:null',
      'Core:DATABASE_URL:true:null',
      'Email:RESEND_API_KEY:true:email',
      'Notifications:EMAIL_REPLY_TO:false:null',
    ],
  )
  assert.ok(!decls.some((d) => d.key === 'REPLACE_ME'), 'a placeholder VALUE is not a variable name')
  assert.ok(!decls.some((d) => d.key === 'NOT_IN_GROUPS'), 'a list checkEnv() never walks reports nothing')
})

test('parsePrismaDatasourceEnv reads only the datasource block', () => {
  const schema = [
    'generator client {',
    '  provider = "prisma-client-js"',
    '}',
    'datasource db {',
    '  provider          = "postgresql"',
    '  url               = env("DATABASE_URL")',
    '  shadowDatabaseUrl = env("SHADOW_DATABASE_URL")',
    '}',
    'model Thing {',
    '  id String @id',
    '}',
  ].join('\n')
  assert.deepEqual(parsePrismaDatasourceEnv(schema), [
    { field: 'url', name: 'DATABASE_URL' },
    { field: 'shadowDatabaseUrl', name: 'SHADOW_DATABASE_URL' },
  ])
  assert.deepEqual(parsePrismaDatasourceEnv('model Thing { id String @id }'), [])
})
